import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryClientProvider";
import { Toaster } from "@/components/ui/sonner";
import { CourseProvider } from "@/context/coursecontext";

// Configure Montserrat font
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify desired weights (e.g., regular and bold)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased bg-[#0A0F1D]`}>
        <QueryProvider>
          <CourseProvider>
        {children}
        </CourseProvider>
        </QueryProvider>
        <Toaster
          richColors
          position="top-center"
          // closeButton
          // toastOptions={{
          //   duration: 5000,
          //   style: {
          //     background: 'var(--popover)',
          //     border: '1px solid var(--border)',
          //     color: 'var(--popover-foreground)',
          //   },
          // }}
          // Increase default duration for all toasts
          duration={5000}
        />

      </body>
    </html>
  );
}